import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React from "react"
import Navbar from "../components/Navbar"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Jopa Foundation',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex-col gap-10 h-full bg-[#05070a]/80`}>
         <Navbar/>
          <div className="pt-11">
             {children}  
          </div>
       
      </body>
    </html>
  )
}
