import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React from "react"
import ContextProvider from "../context/donate.tsx"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Jopa Foundation',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex bg-white h-full`}>
        <ContextProvider>
          {children}
        </ContextProvider>
      </body>
    </html>
  )
}
